### ISSUE TITLE
Destroy method usage problem

### ISSUE THREAD

**Issue by leolux** [tborychowski/perfecttooltip#12]
The documentation is missing an example how to destroy the carousel and I tried two methods without success:
```
Tooltip.destroy(); // <-- Tooltip not defined
$('#tooltip_handling').destroy() // <-- destroy is not a function
```
Any suggestions?

**Comment by tborychowski** [comment]
Hi,
> The documentation is missing an example how to destroy the carousel
what carousel?

if you need to destroy the tooltip, here's the explanation:
as per https://github.com/tborychowski/perfecttooltip/blob/master/js/jquery.tooltip.js#L11, all you need to do is:
```js
$('#tooltip_handling').tooltip('_destroy');
```

## BUT:
In a well designed system, you should not need to `destroy` my tooltip.
The way the tooltip works (if used properly) is - you attach 1 single event to a root container  (or even body) with a selector, e.g. `.has-tooltip`.
The event then recognizes that a hovered element needs a tooltip and creates one on the fly.
And when you move your mouse out of the element - the tooltip is destroyed.
With this setup you can add and remove elements dynamically and there's nothing to clean/`destroy`, as no garbage is left at any time (that's why it's called **perfetct tooltip** :-))

To benefit from this setup, the tooltip should be instantiated like this:

```html
<body>
   <div class="has-tooltip" data-title="tooltip text 1">...</div>
   <div class="has-tooltip" data-title="tooltip text 2">...</div>
</body>
```

and in js:
```js
$('body').tooltip({ selector: '.has-tooltip'  });
```

**Comment by leolux** [comment]
The word "carousel  was a copy-paste mistake. This is the reason for most bugs anyway^^

I knew there has to be some reason for the name "perfect tooltip" and now I know why. Your design makes perfect sence :-)

Thanks for your good explanation!
